export const CATEGORY1_VALUES = [
  "Alimentação",
  "Assinaturas",
  "Mercados",
  "Renda Extra",
  "Outros",
  "Lazer / Esporte",
  "Lazer",
  "Esportes",
  "Compras",
  "Financiamento",
  "Finanças",
  "Interno",
  "Transporte",
  "Mobilidade",
  "Moradia",
  "Saúde",
  "Trabalho",
  "Telefone",
  "Educação",
  "Doações",
  "Pets",
  "Férias",
  "Transferências",
  "Vendas",
  "OPEN",
] as const;

export type Category1 = (typeof CATEGORY1_VALUES)[number];
